package com.gundam.gateway.entity;

import com.gundam.commons.base.BaseEntity;
import lombok.Data;

import java.util.Date;


/**
 * @author kampf
 * @date 2020/4/11 上午11:07
 */
@Data
public class Operation extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_log.UserName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_log.VisitorTime
     *
     * @mbg.generated
     */
    private Date visitorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_log.VisitorService
     *
     * @mbg.generated
     */
    private String visitorService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_log.VisitorUrl
     *
     * @mbg.generated
     */
    private String visitorUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_log.Method
     *
     * @mbg.generated
     */
    private String visitorMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_visit_log.RemoteAddress
     *
     * @mbg.generated
     */
    private String remoteAddress;
}